/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tododemo;

import java.awt.EventQueue;



import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.util.Vector;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.border.EmptyBorder;

import java.sql.ResultSetMetaData;

import javax.swing.JTextArea;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.JScrollPane;

import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.PreparedStatement;
public class todo extends javax.swing.JFrame {

    /**
     * Creates new form todo
     */
    
    Connection con = DB.dbconnect();
    String user;
//    public todo(String user) {
//        this.user = user;
//    }
    
    public todo(String user) {
        initComponents();
        this.user = user;
    }

    private todo() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Task Description");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 170, 30));

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 277, 44));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 277, 170));

        jTable1.setBackground(new java.awt.Color(230, 255, 255));
        jTable1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Task", "Description"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(0, 51, 153));
        jTable1.setRowHeight(24);
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 463, 330));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 153));
        jLabel4.setText("Your ToDo List:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 160, 43));

        jButton2.setBackground(new java.awt.Color(0, 51, 204));
        jButton2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Edit");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 107, 49));

        jButton3.setBackground(new java.awt.Color(0, 51, 204));
        jButton3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Done");
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 490, 107, 49));

        jButton4.setBackground(new java.awt.Color(0, 51, 204));
        jButton4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Add");
        jButton4.setBorderPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 107, 49));

        jButton5.setBackground(new java.awt.Color(0, 51, 204));
        jButton5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("View");
        jButton5.setBorderPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 490, 107, 49));

        jButton6.setBackground(new java.awt.Color(0, 51, 204));
        jButton6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Delete ");
        jButton6.setBorderPainted(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 107, 49));

        jButton7.setBackground(new java.awt.Color(0, 51, 204));
        jButton7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Delete All");
        jButton7.setBorderPainted(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, 110, 49));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 102));
        jLabel8.setText("ToDo");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 153));
        jLabel5.setText("Task");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 50, 43));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 850, 10));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            DefaultTableModel df = (DefaultTableModel)jTable1.getModel();
        		int s  = jTable1.getSelectedRow();
        		int id = Integer.parseInt(df.getValueAt(s, 0).toString());
        		
        		try {
        			String imp = jTextField5.getText();
        			String Description = jTextArea1.getText();
        			if(jTextField5.getText().isEmpty()) {
        				imp = df.getValueAt(s,1).toString();
        			}
        			if(jTextArea1.getText().isEmpty()) {
        				Description = df.getValueAt(s, 2).toString();
        			}
        			PreparedStatement pst = (PreparedStatement) con.prepareStatement("update todo set Task = ? ,Description = ? where id = ?");
        			pst.setString(1, imp);
        			pst.setString(2, Description);
        			pst.setInt(3, id);
        			pst.execute();
        			
        			JOptionPane.showMessageDialog(null, "list updated");
        			jTextField5.setText("");
        			jTextArea1.setText("");
        			
        			int a;
        			PreparedStatement pst1 = (PreparedStatement)con.prepareStatement("select * from todo where uName=?");
                                pst1.setString(1, user);
        			ResultSet rs = pst1.executeQuery();
        			ResultSetMetaData rd = (ResultSetMetaData)rs.getMetaData();
        			a = rd.getColumnCount();
        			DefaultTableModel dff = (DefaultTableModel)jTable1.getModel();
        			df.setRowCount(0);
        			while(rs.next()) {
        				Vector v2 = new Vector();
        				for(int i=1;i<=a;i++) {
        					v2.add(rs.getString("id"));
        					v2.add(rs.getString("Task"));
        					v2.add(rs.getString("Description"));
        				}
        				dff.addRow(v2);
        			}
        			
        		}catch(Exception ec) {
        			ec.printStackTrace();
        		}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
        			String imp = jTextField5.getText();
        			String Description = jTextArea1.getText();
        			if(imp.isEmpty() && Description.isEmpty()) {
        				JOptionPane.showMessageDialog(null, "Null Values are not allowed");
        			}
        			else
        			{
        				PreparedStatement pst = (PreparedStatement) con.prepareStatement("insert into todo(Task,Description,uName) values (?,?,?)");
            			pst.setString(1, imp);
            			pst.setString(2, Description);
                                pst.setString(3, user);
            			pst.execute();
            			JOptionPane.showMessageDialog(null, "task Added");
        			}
        			
        			
        			
        			jTextField5.setText("");
        			jTextArea1.setText("");
        			int a;
        			PreparedStatement pst1 = (PreparedStatement)con.prepareStatement("select * from todo where uName=?");
                                pst1.setString(1, user);
        			ResultSet rs = pst1.executeQuery();
        			ResultSetMetaData rd = (ResultSetMetaData)rs.getMetaData();
        			a = rd.getColumnCount();
        			DefaultTableModel df = (DefaultTableModel)jTable1.getModel();
        			df.setRowCount(0);
        			while(rs.next()) {
        				Vector v2 = new Vector();
        				for(int i=1;i<=a;i++) {
        					v2.add(rs.getString("id"));
        					v2.add(rs.getString("Task"));
        					v2.add(rs.getString("Description"));
        				}
        				df.addRow(v2);
        			}
        		}catch(Exception ec) {
        			ec.printStackTrace();
        		}
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
                try {
        			int a;
        			PreparedStatement pst1 = (PreparedStatement)con.prepareStatement("select * from todo where uName=?");
                                pst1.setString(1,user);
        			ResultSet rs = pst1.executeQuery();
                                PreparedStatement ps = (PreparedStatement)con.prepareStatement("select * from todo where uName=?");
                                ps.setString(1,user);
        			ResultSet rr = ps.executeQuery();
        			ResultSetMetaData rd = (ResultSetMetaData)rs.getMetaData();
        			a = rd.getColumnCount();
        			DefaultTableModel df = (DefaultTableModel)jTable1.getModel();
        			df.setRowCount(0);
                                if(rr.next()==false){
                                    JOptionPane.showMessageDialog(null, "No data in database");
                                }
        			while(rs.next()) {
        				Vector v2 = new Vector();
        				for(int i=1;i<=a;i++) {
        					v2.add(rs.getString("id"));
        					v2.add(rs.getString("Task"));
        					v2.add(rs.getString("Description"));
        				}
        				df.addRow(v2);
        			}
                                
        		}catch(Exception ec) {
        			ec.printStackTrace();
        		}
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed



 DefaultTableModel df = (DefaultTableModel)jTable1.getModel();
        		int s  = jTable1.getSelectedRow();
        		int id = Integer.parseInt(df.getValueAt(s, 0).toString());
        		
        		try {
        			String imp = jTextField5.getText();
        			String Description = jTextArea1.getText();
        			if(jTextField5.getText().isEmpty()) {
        				imp = df.getValueAt(s,1).toString();
        			}
        			if(jTextArea1.getText().isEmpty()) {
        				Description = df.getValueAt(s, 2).toString();
        			}
        			PreparedStatement pst = (PreparedStatement) con.prepareStatement("delete from todo where id=?");
        			pst.setInt(1, id);
        			pst.execute();
        			
        			JOptionPane.showMessageDialog(null, "Successfully deleted");
        			jTextField5.setText("");
        			jTextArea1.setText("");
        			
        			int a;
        			PreparedStatement pst1 = (PreparedStatement)con.prepareStatement("select * from todo where uName=?");
                                pst1.setString(1, user);
        			ResultSet rs = pst1.executeQuery();
        			ResultSetMetaData rd = (ResultSetMetaData)rs.getMetaData();
        			a = rd.getColumnCount();
        			DefaultTableModel dff = (DefaultTableModel)jTable1.getModel();
        			df.setRowCount(0);
        			while(rs.next()) {
        				Vector v2 = new Vector();
        				for(int i=1;i<=a;i++) {
        					v2.add(rs.getString("id"));
        					v2.add(rs.getString("Task"));
        					v2.add(rs.getString("Description"));
        				}
        				dff.addRow(v2);
        			}
        			
        		}catch(Exception ec) {
        			ec.printStackTrace();
        		}
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
                try {
        			PreparedStatement pst = (PreparedStatement)con.prepareStatement("truncate table todo");
        			pst.execute();
        		}catch(Exception ec) {
        			ec.printStackTrace();
        		}
        		
        		try {
        			int a;
        			PreparedStatement pst1 = (PreparedStatement)con.prepareStatement("select * from todo");
        			ResultSet rs = pst1.executeQuery();
        			ResultSetMetaData rd = (ResultSetMetaData)rs.getMetaData();
        			a = rd.getColumnCount();
        			DefaultTableModel df = (DefaultTableModel)jTable1.getModel();
        			df.setRowCount(0);
        			while(rs.next()) {
        				Vector v2 = new Vector();
        				for(int i=1;i<=a;i++) {
        					v2.add(rs.getString("id"));
        					v2.add(rs.getString("Task"));
        					v2.add(rs.getString("Description"));
        				}
        				df.addRow(v2);
        			}
        		}catch(Exception ec) {
        			ec.printStackTrace();
        		}
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(todo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(todo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(todo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(todo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new todo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
